version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: "java -jar ./build/libs/Jdk17_Gradle_Container-1.0-SNAPSHOT.jar"